FROM oven/bun:latest

WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

COPY package.json bun.lock turbo.json ./
COPY apps/backend ./apps/backend
COPY packages ./packages

RUN bun install

EXPOSE 8080

CMD ["bun", "--watch", "apps/backend/src/index.ts"]
